### ISSUE TITLE
Broken export on save

### ISSUE THREAD

**Issue by mo8it** [Myriad-Dreamin/tinymist#1452]
The export on save feature is broken since version 0.12.20. The last version that works for me is 0.12.18.

My config in `languages.toml`:

```toml
[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onSave", formatterMode = "typstyle" }

[[language]]
name = "typst"
language-servers = ["tinymist"]
auto-format = true
```

Starting with version 0.12.20, a PDF is not exported on save (with `:w`). A change is only detected when using commands like `d` to delete and `c` to change. But this actually shouldn't happen since I use `onSave` and not `onType`.
This is probably a problem with the new logic for change detection.

Last version checked: `0.13.4`

I am using the latest version of Helix.
