### ISSUE TITLE
make directory for images pasted from clipboard configurable

### ISSUE THREAD

**Issue by jonas-frey** [Myriad-Dreamin/tinymist#1830]
### Motivation

In tinymist on linux, I noticed that I can paste images from the clipboard (eg screenshots in png format) simply using `ctrl+v`, which copies the image in the directory of the `*.ty` file, and puts something like `#image("image-1.png")` in the `*.ty` file.

This is great, but for my workflow I would like the pasted images to end up in a configurable subdirectory. 

### Description

Add a setting to configure a relative path (or simply a subdirectory), in which images which are pasted via `ctrl+v` are stored.   The paste command should then insert eg `#image("subdir/image-1.png")`.

**Comment by Myriad-Dreamin** [comment]
It is in fact configurable in markdown preview, but I don't like it because it is not easy to make a consistent and perfect solution to paste images in markdown.

My recent idea is adding an `onPaste` configuration (the name should be bikeshedded). I give examples to show design and the subtle design problems for this feature request.

## Simply specify a path to store the image for people who pursue simplicity

For a file `root/doc1/main.typ`, we can allow same path "dsl" as that for the output directory:

```yml
# relative to `root/doc1/main.typ`, store as root/doc1/assets/x.png
onPaste: "$root/$dir/assets"
# store as root/assets/doc1/x.png
onPaste: "$root/assets/$dir"
# store as root/assets/main/x.png
onPaste: "$root/assets/$name"
```

Problems: 
- What if I paste in a sub file, like `root/doc1/sub/chapter1.typ`? Then what're the value of `$dir` and `$name`?
- in the third case, we would like to store images "flatten" into the root assets directory, but all the documents might have file named "main.typ".

## Scripting the processing

If the string starts and ends with "{}", it is viewed as a typst script. Before adding more features, let's rewrite the above dsl into typst:

```yml
# store to root/doc1/assets/x.png
onPaste: '{ root; dir; "assets" }'
# store to root/assets/doc1/x.png
onPaste: '{ root; "assets"; dir }'
# store to root/assets/main/x.png
onPaste: '{ root; "assets"; name }'
```

Problems: 
- Much more complex.

## Spliting the assets by mime

```yml
onPaste: '{ import "@local/asset-handler:0.1.0": handle; handle(inputs) }'
```

```typ
#let handle((mime, mainFilePath, root, name, ..)) = if is-image(mime) {
  root; "assets/images"; name
} else {
  root; "assets/files"; name
}
```


## Spliting the assets and process it

```typ
#let handle((mime, mainFilePath, root, name, ..)) = if is-image(mime) {
  (
    path: { root; "assets/images"; name },
    // insert by custom snippet, for example, converting images to grayscale
    insert: `import "@preview/grayness:0.3.0": image-grayscale; image-grayscale(read($1, encoding: none))`.text
  )
} else {
  todo()
}
```
