### ISSUE TITLE
Cargo.lock is broken

### ISSUE THREAD

**Issue by Ciflire** [Myriad-Dreamin/tinymist#24]
**Describe the bug**
Hi i'm trying to package your project with nix, and it fails, some sources are missing, typst-preview for example
Could you please regenerate that correcly so it can be easily used (sry i'm not a rust dev *yet* )

**Comment by Myriad-Dreamin** [comment]
Hi, I should leave typst-preview as an optional dependency, then you can compile it without preview functionality.

**Comment by Myriad-Dreamin** [comment]
it is still broken by:
```toml
[patch."https://github.com/Enter-tainer/typst-preview"]
typst-preview = { path = "external/typst-preview" }
```
