### ISSUE TITLE
Just a question: Where does tinymist get completion data from?

### ISSUE THREAD

**Issue by kdog3682** [Myriad-Dreamin/tinymist#740]
I am trying to write a typst plugin, and one of the things I'm looking for is completion data like:

```
func: table
args: 
   - name: columns
     desc: how many columns the table will have 

... et cetera
```

I've been skimming through tinymist's source code to see if this data shows up, but I haven't been able to find any. I was wondering how do you collect the data?

Thanks!
