### ISSUE TITLE
Document formatting unavailable in editor

### ISSUE THREAD

**Issue by MrLego8-9** [Myriad-Dreamin/tinymist#799]
**Describe the bug**

The formatting option is unavailable in Kate and Helix.

While Kate is not officially supported by tinymist, it implements the LSP protocol.

Here are the LSP settings in Kate (they're the same in Helix)

```json
"settings": {
				"exportPdf": "onSave",
				"formatterMode": "typstyle"
			}
```

From what I saw in other issues, it may be due to dynamic registration.

Is there any way to fix this ?

**Package/Software version:**
(From arch linux repos)
tinymist extension version: `v0.12.0`. Get it by `tinymist --version` in terminal.
```plain
tinymist
Build Timestamp:     2024-11-11T13:20:38.000000000Z
Build Git Describe:  VERGEN_IDEMPOTENT_OUTPUT
Commit SHA:          VERGEN_IDEMPOTENT_OUTPUT
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.12.0
Typst Source:        git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9
```

**Comment by Eric-Song-Nop** [comment]
I am not familiar with Kate, while the formatterMode setting works on my side on helix:
```toml
[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", formatterMode = "typstyle" }

[[language]]
name = "typst"
language-servers = ["tinymist"]
```

It would be nice if you can provide us with your lsp.log file from the editor.
