### ISSUE TITLE
MVP project-level configuration

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#900]
Rearranged from the cold issue #530 

**Motivation**

Many clients other than VS Code provide bad experience on editing typst documents consisting multiple files.

**Description**

Possible MVP design. We will add `tinymist.input` section to `typst.toml`:

```toml
[tinymist]
# versioning the input (entry) resolver
resolver = "v0.0.0-beta"

[[tinymist.input]] # Some entry in this project
name = "Project 1"
entry = "main.typ"

[[tinymist.input]] # Some other entry in this project
name = "Project 2"
entry = "main2.typ"
sys.input = {
  x = "y"
}
```

Feature 1 (may change in future): The configuration in nearest `typst.toml` is used by inner documents. If the `typst.toml` files are nested, the configuration in outer `typst.toml` files are never used by inner documents. The distance "nearest", "outer", "inner" are determined by their file paths.
Feature 2: If some `tinymist.input` is used, tinymist will "pin" the entry as the main file to response lsp and preview requests.
Feature 3: If a file belongs to multiple `tinymist.input`, the first matched one is used in the `typst.toml` file.
Feature 4: If user switches between files and the files belongs to a same `tinymist.input`, tinymist will keep use the same `tinymist.input` and will not detect the entry file again.

**Implementation**

MVP can only support `tinymist.input.name` and `tinymist.input.entry` first. Users must restart the server to reload the configurations.

**Questions**

Question: It may cause slow start, as tinymist must know all file dependencies correctly, but we have already handle module dependencies resolution as much as possible by static code analysis, which won't trigger any typst compilation (`typst::compile`), and we can ignore file switches between non-source files. https://github.com/Myriad-Dreamin/tinymist/blob/3ed4323089863a52d9739214e19a999c86dba79d/crates/tinymist-query/src/syntax/module.rs#L17-L22
